# Generated by Django 2.1 on 2018-10-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educol', '0004_auto_20181013_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
