# Generated by Django 2.1 on 2018-10-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educol', '0005_evento_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/fotosapp/'),
        ),
    ]
